development:
  adapter: postgresql
  encoding: unicode
  database: cara_development
  username: tyler
  password:
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: cara_test
  username: tyler
  password:
  host: localhost
  port: 5432
